server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invillia
    username: invillia
    password: invilli@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
        format_sql: false
  jackson:
    serialization.write_dates_as_timestamps: false
    deserialization.adjust_dates_to_context_time_zone: true
    time-zone: UTC
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

scheduler.pool.size: 10
scheduler.payment.process.cron: 0 0/1 * 1/1 * ?
