server:
  contextPath: /invillia
spring:
  application:
    name: Invillia Challange
  datasource:
    url: jdbc:mysql://localhost:3306/invillia
    username: invillia
    password: invilli@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
        format_sql: false
  jackson:
    serialization.write_dates_as_timestamps: false
    deserialization.adjust_dates_to_context_time_zone: true
    time-zone: UTC
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
flyway:
  locations: classpath:/db/migration
  check-location: true
  sqlMigrationPrefix: V
  sqlMigrationSeparator: __
  sqlMigrationSuffix: .sql
  validateOnMigrate: true
  schemas: invillia
