server:
  contextPath: /invillia
spring:
  application:
    name: Invillia Challange
  datasource:
    url: jdbc:mysql://localhost:3306/invillia
    username: invillia
    password: invilli@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
        format_sql: false
