= Overview
    This is a API documentation of Invillia challenge.

== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `202 Accepted`
| A new resource has been accepted successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

= Store Resources

== Create Store
operation::create-store-success[snippets='http-request,request-fields,curl-request,http-response,response-fields']

== Update Store
operation::update-store-success[snippets='http-request,request-fields,curl-request,http-response']
operation::not-found-store[snippets='http-request,request-fields,http-response']

== Query Store
operation::find-store-success[snippets='http-request,request-fields,curl-request,http-response,response-fields']

